apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pv-volume-claim1
spec:
  selector:
    matchLabels:
      volume: es-pv1-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local
